### ISSUE TITLE
Is there any plan for Unreal 5?

### ISSUE THREAD

**Issue by Qinka** [unrealgt/unrealgt#11]
Unreal 5 is released. Is there any plan for Unreal 5?

**Comment by lolleko** [comment]
Have you tried it. Since UE5 is mostly backwards combatible with UE4 projects&plugins it may work already.

**Comment by Qinka** [comment]
FHitResult was changed in UE5. FHitResult no longer has member ``Actor'' (VS error  C2039).

**Comment by lolleko** [comment]
Ah okay, should be an easy fix. I think you can just replace it with `FHitResult::GetActor()` 
I will try to do an update soon

**Comment by lolleko** [comment]
Support added in [b2e787d](https://github.com/unrealgt/unrealgt/commit/b2e787d592c761214eb10cc9df9df9fe562ec2af)
