### ISSUE TITLE
Depth image

### ISSUE THREAD

**Issue by charleshamesse** [unrealgt/unrealgt#6]
Hi,
Thanks for publishing this work!
I've encountered an error while trying to generate depth maps, I get this output with the debugger:

![image](https://user-images.githubusercontent.com/10261071/81507490-192dc580-92fe-11ea-8b0a-3ffba21d657a.png)

And the exported files look the same as the left image in the above picture. 
Will make a PR if I can find a fix. Until then, any help would be appreciated. Thanks!

- Platform: Ubuntu 18.04
- Unreal Engine version: 4.22.3

**Comment by lolleko** [comment]
That depth definitely looks wrong. I have never seen artefacts like that before.

Do you have anti aliasing or any post processing settings enabled? There is a chance that these settings conflict with the depth calculation which also happens in a post processing shader.

**Comment by charleshamesse** [comment]
I just made sure all post processing settings were disabled and got the same result. Maybe it's a UE version issue? Did you test it on 4.22.3 by any chance? 

By the way the image and the image normal generators work perfectly. Thanks!

**Comment by lolleko** [comment]
This is how the depth generation looks for me with the example generator from `UnrealGT Content > Examples >Depth` (you have to enable show plugin content in the content browser) UE 4.24

![image](https://user-images.githubusercontent.com/4759511/81666131-e856a900-9441-11ea-975f-8d2dc0d15472.png)
![image](https://user-images.githubusercontent.com/4759511/81666155-f278a780-9441-11ea-97d3-c4f880d00cf1.png)

I startet writting the plugin with 4.22 but switched to 4.23 during development, so there is a really small chance that its related to the UE version. I recently fixed the plugin for 4.24 so you should use 4.24 if possible.

**Comment by charleshamesse** [comment]
Thanks! I wanted to try on 4.24 but for some reason it keeps on crashing on my current machine. I'll try and fix that and let you know.

**Comment by charleshamesse** [comment]
Hi, I updated to 4.24.3 and I can confirm generating depth maps works as expected.

**Comment by lolleko** [comment]
Great! I will change the supported UE versions to 4.24/4.25 in the docs. Because if 4.22 doesn't work im pretty sure 4.23 will not work aswell with the 4.24 fixes.
