### ISSUE TITLE
I am only getting 3D world coordinates for GTActorInfo (UE 4.26)

### ISSUE THREAD

**Issue by chophilip21** [unrealgt/unrealgt#9]
I know that you guys have created a function to convert the World Coordinates into 2D Pixel Coordinates, but when I try to output that using FileStreamer, I only get the Actor Class and World 3D coordinates on the output file. 

Am I doing something wrong?

**Comment by chophilip21** [comment]
SK_Wolf -180.000000 30.000000 20.000000 SK_Wolf2 -240.000000 -140.000000 20.000000 SK_Wolf3 -230.000000 190.000000 20.000000

**Comment by chophilip21** [comment]
Never mind. I found this p<FString, FStringFormatArg> GlobalProperties{
            {TEXT("WorldLocation"), Vector3DToFormattedString(TrackedActor->GetActorLocation())},
            {TEXT("WorldRotation"), RotatorToFormattedString(TrackedActor->GetActorRotation())},
            {TEXT("ScreenLocation"), Vector2DToFormattedString(ScreenLocation)},
            {TEXT("ScreenLocationNormalized"), Vector2DToFormattedString(ScreenLocationNormalized)},
            {TEXT("ScreenBoundingBox"), Box2DToFormattedString(ScreenBoundingBox)},
            {TEXT("ScreenBoundingBoxNormalized"),
             Box2DToFormattedString(ScreenBoundingBoxNormalized)},
            {TEXT("ActorName"), TrackedActor->GetName()},
            {TEXT("MeshName"), MeshName}};

**Comment by chophilip21** [comment]
Unfortunately it seems like your bounding box functions are not really working. I see that these are all 10 points, but they don't really appear to be x1 y1 x2 y2 format. If I try to plot these points they are all completely off.

object name : Pig_BP5 bounding_box: ['311.413025', '844.176086', '524.417603', '982.795959', '417.915314', '913.486023', '106.502289', '69.309937', '213.004578', '138.619873']
object name : Pig_BP7 bounding_box: ['0.000000', '819.979614', '337.149872', '1079.000000', '168.574936', '949.489807', '168.574936', '129.510193', '337.149872', '259.020386']
object name : Pig_BP8 bounding_box: ['0.000000', '837.272522', '0.000000', '1079.000000', '0.000000', '958.136230', '0.000000', '120.863739', '0.000000', '241.727478']

If I turn on accurate bounding box option on, all the points just become 0.

**Comment by lolleko** [comment]
Do you have bOnlyTrackOnScreenActors enabled?
Because 2D bounding boxes won't work (and dont make sense) for offscreen actors because the inverse projection won't work.

**Comment by chophilip21** [comment]
Thanks a lot for getting back! Your plugin is amazing and has all the features I need, but the documentation is really minimal. Would be nice to have more examples (your "advanced examples" tab seems to be broken too. Nothing shows up here).  

On UE4 end I have "ony track on screen actors" enabled. Below is a screenshot.

![Capture](https://user-images.githubusercontent.com/16346590/133702637-52f79178-839b-4c25-9c13-b8497356d084.JPG)

Am I missing something here?

**Comment by lolleko** [comment]
Did you have a look at the content/examples folder?
I am aware that the documentation is lacking but sadly I do not have the time to actively maintain this projet anymore.

Screenshot looks good.

Looks like the "IsActorOnScreen" part is unfinished or WIP (I don't remember) try playing around with https://github.com/unrealgt/unrealgt/blob/master/Source/UnrealGT/Private/Generators/Text/GTActorInfoGeneratorComponent.cpp#L262

**Comment by chophilip21** [comment]
Okay thanks. I'll look at that script and see what I can do.

**Comment by lolleko** [comment]
Oh, I think I might found the issue, try setting the minimal bounding box to something other than zero (0,0). Doesn't matter what just not zero.

culprit:
https://github.com/unrealgt/unrealgt/blob/master/Source/UnrealGT/Private/Generators/Text/GTActorInfoGeneratorComponent.cpp#L289

**Comment by chophilip21** [comment]
I have set minimal X and Y to 20.0 and the results look a bit more reasonable.

However, one strange thing is that as the below segmentation map suggests, there should be 9 characters visible in the scene, 

![0_20210917T140922033Z](https://user-images.githubusercontent.com/16346590/133854301-6f010f9a-3c4a-43b0-97f7-7242645bddf2.png)
 
but the output annotation produces data for 10 characters when using parameter {ActorName} {ScreenBoundingBox},
```
Pig_eat_5 641.919006 815.986633 1358.553955 1079.000000 1000.236450 947.493286 358.317474 131.506683 716.634949 263.013367,
Pig_eat_8 0.000000 659.493896 151.820984 787.512939 75.910492 723.503418 75.910492 64.009521 151.820984 128.019043,
Pig_eat_9 911.275085 743.852478 1182.902222 867.886780 1047.088623 805.869629 135.813568 62.017151 271.627136 124.034302,
Pig_sleep_3 161.534607 756.863831 378.897278 867.475647 270.215942 812.169739 108.681335 55.305908 217.362671 110.611816,
Pig_sleep_5 0.000000 775.613098 491.550293 1079.000000 245.775146 927.306519 245.775146 151.693451 491.550293 303.386902,
Pig_sleep_6 559.944885 654.199646 828.154663 796.591125 694.049805 725.395386 134.104889 71.195740 268.209778 142.391479,
Pig_sleep_7 152.973511 652.422241 478.716888 793.699402 315.845215 723.060791 162.871689 70.638580 325.743378 141.277161,
Pig_BP3 0.000000 771.131042 21.923733 873.288696 10.961866 822.209839 10.961866 51.078827 21.923733 102.157654,
Pig_BP5 324.170044 847.863831 534.083435 1023.785889 429.126740 935.824829 104.956696 87.961029 209.913391 175.922058,
Pig_BP_test 636.203857 693.850708 935.163635 924.485779 785.683716 809.168213 149.479889 115.317535 298.959778 230.635071
```
Maybe the result will change if I further increase the size limit. 

Another important question is--- how am I supposed to interpret above 10 digits for each instance? Are these [X1 Y1 X2 Y2 X3 Y3...]  Coordinates? If I can find out what each points signify, I can convert them into YOLO requirements like [X_center, Y_center, width, height].

**Comment by lolleko** [comment]
Yeah, maybe there is some, pig that is barely on-screen that is being detected, try tweaking the min bounding-box values or rewrite the IsActorOnScreen function to better fit your needs.


As for the values, you can define the output format for bounding boxes in the "Output Format" category of the actor info component.

The default value can be found here: 

[`{Min} {Max} {Center} {Extent} {Width} {Height}`](https://github.com/unrealgt/unrealgt/blob/master/Source/UnrealGT/Private/Generators/Text/GTActorInfoGeneratorComponent.cpp#L30)
for YOLO you will probably want `{Center} {Width} {Height}`
If you want to adjust how the vector2d (e.g. center) is formatted, just change the `FormatVector2DString` property.

**Comment by lolleko** [comment]
I actually found the code that I used to live debug YOLO using 2 TCP streams (image + actor info) from UE4.
It is super hacky and undocumented, but maybe it helps you https://gist.github.com/lolleko/439ed267a7253d4091ecf2edf8deaf4a

**Comment by chophilip21** [comment]
Thanks a lot! Now everything is making sense! I tried drawing a box using {Center} {Width} {Height} and it looks much much better. 

One final concern is that the bounding boxes are a little too big. 

![0_20210917T163531905Z](https://user-images.githubusercontent.com/16346590/133864563-353ad298-755f-4cab-825d-5aca64dd79dd.png)

I'm not entirely sure if changing FormatVector2DString will fix this? I'm wondering if {Min} {Max} or {Extent} can be any useful in terms of scaling down the size of the bounding boxes in a reliable way. I can try blindly scaling down the bounding box by constant but that doesn't seem to be smart at all. 

I see that the YOLO example you provided is very similar to my code, except that I am using the none-normalized coordinates.

**Comment by chophilip21** [comment]
And the function that applies "Accurate Bounding Box" seems to be incomplete, as the results all become 0. But function "Apply Closing" definitely makes the results better.

**Comment by lolleko** [comment]
The Accurate bounding boxes should make the BBoxes a lot better. The ones from your screenshot are definitely not accurate.
Can you open the debug window and select the actorinfo component you are using?
It should look somewhat like this with accurate bounding boxes turned on:
![bounding_box_accurate_closing](https://user-images.githubusercontent.com/4759511/133884806-70296236-b5f3-4b97-b2e3-e304e45df40c.PNG)

**Comment by chophilip21** [comment]
Interesting. I totally forgot about using your debugger inside Plugin and I was plotting the points just using my Python code.

This is how the scene is structured at the moment. I have been adjusting scales on the objects and some of them have collision maps that are off,

![collision](https://user-images.githubusercontent.com/16346590/133898164-e70c85b1-fa5e-493c-9b4b-c17118fb5be1.JPG)

But if you look at the segmentation map, everything looks really good. 

![segmentation](https://user-images.githubusercontent.com/16346590/133898207-c54cf2ef-e765-428c-8eea-5cea44ecb2de.JPG)

But when I debug actor info (without accurate bb), I get below, which is way too big for all instances.
 
![without_precise_bb](https://user-images.githubusercontent.com/16346590/133898221-90918279-5ebb-4e39-9428-539f6aaf2abc.JPG)

When I turn on the accurate bounding box setting, some how the bounding boxes do show up, although the file streamer delivers a completely blank txt file when this setting is turned on. 

![accurate](https://user-images.githubusercontent.com/16346590/133898237-5e44e027-1c1b-4ea9-b4f7-1b67db1c76a5.JPG)

There is less noise when the accurate setting is turned on, but some of the pigs lose their bounding boxes. Do you think there is something wrong with the scene itself?

**Comment by lolleko** [comment]
Mhhh there is definitely  something wrong because with the accurate bbox option you should get pixel perfect bounding boxes  (as shown in my screenshots).
Do you by any chance have a separate segmentation generator active at the same time? This would lead to problems as it is currently not possible to do 2 different segmentation passes of the same objects.

I am currently abroad and have no access to a computer with UE4 so i can't look into it myself.
One suggestion if you can't figure out the issue with the plugin/your setup is to just generate a segmentation map that assigns each pig a unique color (use the random color option) and calculate the bounding boxes manually in python.

**Comment by chophilip21** [comment]
Thanks a lot for helping out while being abroad!

I tried removing segmentation map generator (accurate bb still enabled) and somehow the results improved.  

![strange_result](https://user-images.githubusercontent.com/16346590/133906434-1ab31b13-d036-4c44-a6b0-b513de565852.JPG)

I don't know what the issue was exactly, but regardless of adding the segmentation generator back on, the bounding boxes are much better. The results on smaller pigs are perfect, but results on a bigger pigs are still off. 

I need to get the project going so I think I'll go ahead and try your suggestions of using the segmentation masks to create bounding box. Probably this isn't as easy as it sounds, because you need to be able to look for consecutive pixels and then derive bounding box from that, but at least it should be much easier than debugging c++ code. I don't know much about c++ so I have asked a friend of mine to give me some hand on this.

**Comment by lolleko** [comment]
> Thanks a lot for helping out while being abroad!


You're welcome, sorry I can't be of more help. Pretty much just brainstorming potential solutions :D

---

> I don't know what the issue was exactly, but regardless of adding the segmentation generator back on, the bounding boxes are much better. The results on smaller pigs are perfect, but results on a bigger pigs are still off.

It depends on the initialization order of the generators when the scene is started (the segmentation generator will override the segmentation settings of the actor info generator if spawned after the actor info generator by the engine).
Like I said, I don't recommend using both segmentation generator and actorinfo generator (with accurate bboxes) at the same time, since one of the two will generate incorrect data.

---

The larger bounding boxes always contain two or more pigs perfectly, there could be to possible reasons for that:

1. The filter recognizes them as one object (maybe they are part of the same Blueprint/Actor?)
2. The way the accurate bboxes work is by segmenting each pig with a random colour. Then the inaccurate bounding box is used with the segmentation map, to shrink the bounding boxes to contain only the pixels of the corresponding colour for each pig. The only problem is, that there is a limit of 255 colours, so it is possible that 2 pigs get the same colour, resulting in incorrect bbox calculation since they will be considered the same object by the bboxes.
This can only happen once you have more than 255 pigs in your scene, so I doubt that's the case here?

Another idea: 

Since I have never personally tried the plugin with skeletal, meshes. Try converting the skeletal meshes to static meshes.

---
> I need to get the project going so I think I'll go ahead and try your suggestions of using the segmentation masks to create bounding box. Probably this isn't as easy as it sounds, because you need to be able to look for consecutive pixels and then derive bounding box from that, but at least it should be much easier than debugging c++ code. I don't know much about c++ so I have asked a friend of mine to give me some hand on this.

You can use opencv's contour features:
- https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_contours/py_contour_features/py_contour_features.html#contour-features
- https://docs.opencv.org/3.4/da/d0c/tutorial_bounding_rects_circles.html

also try googling "segmentation to bounding boxes" I am certain that has been done before.

**Comment by chophilip21** [comment]
I have just tried implementing the opencv contour approach on the segmentation map and it is quite sucessful, as you can see.

![10_20210917T163532818Z](https://user-images.githubusercontent.com/16346590/133909900-36f8a55d-55b9-4d89-bba1-fc443c7dc6c1.png)

But the problem of this approach, is that it cannot deal with occulusions properly. When the Pig is behind the metal bar, for example, it appears as three blobs of pixels.

![7_20210917T163532523Z](https://user-images.githubusercontent.com/16346590/133909928-72734b44-bb06-49a2-b26c-2607ba7804dd.png)

I have implemented heuristic that merges bounding boxes when the size of the pixel blob is really small to the nearest large bounding box (based on Euclidean distance), but this merges perfectly fine pig that is just small because it's far away. I'll need to think a bit more on this, as training another model based on this data will lead to pretty bad results.

**Comment by lolleko** [comment]
Okay than maybe try a different approach

1. use the random color option to assign each pig an (almost) unique color
2. Iterate over all pixels, if the pixel has a color that has not been seen previously add that color to a list
3. for each found color, iterate over all pixels and if the pixel matches the current color accumulate the pixel coordinates into a bounding box

step3 pseudo code
```
foreach color {
    bbox = 0,0
    foreach pixel {
        if pixel.color == color {
            bbox.min.x = min(bbox.min.x, pixel.x)
            bbox.min.y = min(bbox.min.y, pixel.y)

            bbox.max.x = max(bbox.max.x, pixel.x)
            bbox.max.y = max(bbox.max.y, pixel.y)
        }
     }
     bboxlist.append(bbox)
}
```

**Comment by chophilip21** [comment]
That is an indeed good idea, and the Python code that I just wrote based on the pixel intensity works perfectly. Below is the result:

![0_20210919T000416006Z](https://user-images.githubusercontent.com/16346590/133938702-d518ca60-76c7-406e-8ac0-38bddefa4261.png)

![155_20210919T000431248Z](https://user-images.githubusercontent.com/16346590/133938729-bd12f306-fbd1-418d-b26e-05dee44ff5a0.png)

Thanks a lot for all the help!
